import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal'], // You can add more styles if needed
});

export const metadata: Metadata = {
  title: "Empowering Tamil Nadu with Smarter Solar Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
              dangerouslySetInnerHTML={{
                  __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-W7NCP52R');`,
              }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${openSans} antialiased`}
      >
        <div dangerouslySetInnerHTML={{
        __html: `
          <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W7NCP52R"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        `
      }} />
        {children}
      </body>
    </html>
  );
}
