import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal'], // You can add more styles if needed
});

export const metadata: Metadata = {
  title: "Empowering Tamil Nadu with Smarter Solar Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.jpg" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${openSans} antialiased`}
      >
        <script type="text/javascript" src="https://seobot.centilio.com/js/centilio_connector.js"></script>
        <script type="text/javascript">centilio_connector_init.track(441);</script>
        {children}
      </body>
    </html>
  );
}
